- data_structures/serviceList.cpp
- main-test.c
- model/member.cpp
- model/person.cpp
- model/person.h
- model/provider.cpp
IT'S WORKING! Someone glance through and accept this plssssss
(anyone can do it, just need someone to do it ya know)
> WE ARE ALIVE

- data_structures/serviceList.h
- data_structures/test/datacenter_test.cpp
- data_structures/test/datacenter_test.h
- main-test.c
- main.cpp
make it as usual and then run `./ChocAn d` to call the function in data_structures/test/datacenter_test.cpp, this should give @abbie-utley and @tgomez22 the ability to start running and debugging their code.
> Added testing capability

- Makefile
- data_structures/serviceList.h
- data_structures/test/datacenter_test.cpp
- data_structures/test/datacenter_test.h
- main-test.c
- main.cpp
Fixed the makefile to actually function!
> New makefile

- main.cpp
- testing/catch.hpp
- testing/tests.cpp
Tests can be written in testing/tests.cpp!
> Add Catch testing framework

- model/entity.cpp
- model/entity.h
Just changed ID to be 10 for the backslack zero for strings
> Kristinbell

- model/entity.cpp
had to allow the user the ability to add too much so that we could say it was wrong LOL
> changed to allow user to enter too much

- main.cpp
In case the user types where they should scan I created an error message instead of just aborting the whole program. It will continue to ask for them to scan the number until they do it.
> changed gives error if user types when scan

- data_structures/serviceList.cpp
I removed a duplicate destructor and duplicate remove function that were from the merging Abbie and Tristan's code. I also removed the weird comments git put in during the merging process.
> Fixed serviceList.cpp (see below)

- main.cpp
Run catch tests found in testing/tests.cpp by using ./Chocan t on the command line
(As a side note, unsure why the indentation is getting screwed up when pushed to github, on my local file it looks clean)
> Add case for catch testing to switch statement

- data_structures/serviceList.cpp
- data_structures/serviceList.h
See serviceList.h and .cpp for them. Left comments as well. It compiles
> Prototype and implementation for Chris added

- data_structures/personList.cpp
- data_structures/personList.h
- data_structures/serviceList.cpp
- data_structures/serviceList.h
- hierarchy/service.cpp
- hierarchy/service.h
- main.cpp
changed the function stuff to deal with ints so we could use the exit function that asks if they want to exit for sure. A bunch of stuff is still truncated.
> changed to make the exit function work

- datacenter.cpp
- datacenter.h
- interfaces/provider-term.cpp
- interfaces/provider-term.h
- interfaces/util-term.cpp
- interfaces/util-term.h
a stubby bunch of provider stuff
> added a whole bunch of provider stuff

- datacenter.cpp
- datacenter.h
- model/entity.cpp
- model/entity.h
- model/tString.cpp
- model/tString.h
I added in the datacenter's data members. I think the constructor is okay being empty since the underlying data are objects with their own constructors. I implemented the three validate functions as well
> Added datacenter.cpp  and .h stuff. See below

- hierarchy/service.cpp
- hierarchy/service.h
- interfaces/provider-term.cpp
- interfaces/provider-term.h
- interfaces/util-term.cpp
- interfaces/util-term.h
- interfaces/validation-term.cpp
> added a bunch of stuff for provider interface

- datacenter.cpp
- datacenter.h
- interfaces/provider-term.cpp
- interfaces/provider-term.h
trying to get service record input to work
> trying to deal with service record input

- data_structures/serviceList.h
- datacenter.cpp
- datacenter.h
- hierarchy/service.cpp
- hierarchy/service.h
- interfaces/provider-term.cpp
- interfaces/provider-term.h
- interfaces/util-term.cpp
- interfaces/util-term.h
- model/entity.cpp
many things unfinished...thought I should push up though
> working on creating service record

- data_structures/personList.h
- data_structures/serviceList.cpp
- data_structures/serviceList.h
This function is currently waiting on member/provider data setters
> Add structure for serviceList readIn function

- hierarchy/service.cpp
Hahahahaha not using keyword new ...
> Resolve compiler error in getDescription

- datacenter.cpp
- hierarchy/service.cpp
I cannot believe this is actually working
> Call service writeOut after adding a service to write to disk

- datacenter.cpp
- datacenter.h
- interfaces/provider-term.cpp
- main.cpp
Reverts tgomez22/cs300_group2#86
> Revert "Chris"

- datacenter.cpp
- datacenter.h
- model/entity.cpp
- model/entity.h
> updated report functions and service compare functions
